In [1]:
%matplotlib inline
from IPython.display import display,Latex,Math,HTML
import sympy as sym
import math
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import numpy as np

<center>
<hr>
<font size="20" color='Blue' >Gauss Elimination</font>
<hr>
</center>

In [2]:
mat = np.array([[25,5,1],[64,8,1],[144,12,1]])
vec_b = np.array([106.8,177.2,279.2])
print(mat)
print(vec_b)

[[ 25   5   1]
 [ 64   8   1]
 [144  12   1]]
[106.8 177.2 279.2]


In [4]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}} 
                  \\Huge {{{mat[0,0]}}} & \\Huge {{{mat[0,1]}}} & \\Huge {{{mat[0,2]}}}\\\\[1em]
                  \\Huge {{{mat[1,0]}}} & \\Huge {{{mat[1,1]}}} & \\Huge {{{mat[1,2]}}}\\\\[1em]
                  \\Huge {{{mat[2,0]}}} & \\Huge {{{mat[2,1]}}} & \\Huge {{{mat[2,2]}}}      
            \\end{{bmatrix*}} 
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2\\\\[1.8em]
                  \\Huge a_3
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{vec_b[0]}}}\\\\[1em]
                  \\Huge {{{vec_b[1]}}}\\\\[1em]
                  \\Huge {{{vec_b[2]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

<IPython.core.display.Latex object>

In [5]:

 
n = 3
a = np.concatenate((mat,vec_b.reshape(-1,1)),axis=1)

x = np.zeros(n)
print('forward elimination\n')
for i in range(n):
    print(a,end='\n\n')
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
print('backward substitution\n')
x[n-1] = a[n-1][n]/a[n-1][n-1]
print(f"x[{n-1}] = {a[n-1][n]}/{a[n-1][n-1]} = {x[n-1]}",end='\n\n')
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    t=0 
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
        t += a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
    sign = '+' if t<0 else '-'
    print(f"x[{i}] = ({a[i][n]} {sign} {abs(t)})/{a[i][i]} = {x[i]}", end='\n\n')
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.5f' %(i,x[i]), end = '\t')

forward elimination

[[ 25.    5.    1.  106.8]
 [ 64.    8.    1.  177.2]
 [144.   12.    1.  279.2]]

[[  25.       5.       1.     106.8  ]
 [   0.      -4.8     -1.56   -96.208]
 [   0.     -16.8     -4.76  -335.968]]

[[ 25.      5.      1.    106.8  ]
 [  0.     -4.8    -1.56  -96.208]
 [  0.      0.      0.7     0.76 ]]

backward substitution

x[2] = 0.7599999999999909/0.6999999999999993 = 1.0857142857142739

x[1] = (-96.20800000000003 + 1.6937142857142673)/-4.800000000000001 = 19.690476190476197

x[0] = (106.8 - 99.53809523809527)/25.0 = 0.2904761904761893


The solution is: 
X0 = 0.29048	X1 = 19.69048	X2 = 1.08571	

<center>
<hr>
<font size="20" color='Blue' >Gauss Elimination with Pivot </font>
<hr>
</center>

In [6]:
mat = np.array([[144,12,1],[25,5,1],[64,8,1]])
vec_b = np.array([279.2,106.8,177.2])
print(mat)
print(vec_b)

[[144  12   1]
 [ 25   5   1]
 [ 64   8   1]]
[279.2 106.8 177.2]


In [ ]:
Latex(f""" \\begin{{equation*}}
            \\begin{{bmatrix*}} 
                  \\Huge {{{mat[0,0]}}} & \\Huge {{{mat[0,1]}}} & \\Huge {{{mat[0,2]}}}\\\\[1em]
                  \\Huge {{{mat[1,0]}}} & \\Huge {{{mat[1,1]}}} & \\Huge {{{mat[1,2]}}}\\\\[1em]
                  \\Huge {{{mat[2,0]}}} & \\Huge {{{mat[2,1]}}} & \\Huge {{{mat[2,2]}}}      
            \\end{{bmatrix*}} 
            \\begin{{bmatrix*}}
                  \\Huge a_1\\\\[1.8em]
                  \\Huge a_2\\\\[1.8em]
                  \\Huge a_3
            \\end{{bmatrix*}}=
            \\begin{{bmatrix*}}
                  \\Huge {{{vec_b[0]}}}\\\\[1em]
                  \\Huge {{{vec_b[1]}}}\\\\[1em]
                  \\Huge {{{vec_b[2]}}}
            \\end{{bmatrix*}}
      \\end{{equation*}}
""")

In [ ]:
def rnd(x,n=2):
    t = 10**n
    return math.floor(x*t)/t

n = 3
a = np.concatenate((mat,vec_b.reshape(-1,1)),axis=1)

x = np.zeros(n)
print('forward elimination\n')
for i in range(n):
    print(a,end='\n\n')
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
print('backward substitution\n')
a[n-1][n]=rnd(a[n-1][n])
a[n-1][n-1]=rnd(a[n-1][n-1],1)
x[n-1] = rnd(a[n-1][n])/rnd(a[n-1][n-1])
print(f"x[{n-1}] = {a[n-1][n]}/{a[n-1][n-1]} = {x[n-1]}",end='\n\n')
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    t=0 
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
        t += a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
    sign = '+' if t<0 else '-'
    print(f"x[{i}] = ({a[i][n]} {sign} {abs(t)})/{a[i][i]} = {x[i]}", end='\n\n')
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.5f' %(i,x[i]), end = '\t')

In [ ]:
n = 3
a = np.concatenate((mat,vec_b.reshape(-1,1)),axis=1)

x = np.zeros(n)
print('forward elimination\n')
for i in range(n):
    print(a,end='\n\n')
    for j in range(i+1, n):
        ratio = a[j][i]/a[i][i]
         
        for k in range(n+1):
            a[j][k] = a[j][k] - ratio * a[i][k]
 
print('backward substitution\n')
x[n-1] = a[n-1][n]/a[n-1][n-1]
print(f"x[{n-1}] = {a[n-1][n]}/{a[n-1][n-1]} = {x[n-1]}",end='\n\n')
for i in range(n-2,-1,-1):
    x[i] = a[i][n]
    t=0 
    for j in range(i+1,n):
        x[i] = x[i] - a[i][j]*x[j]
        t += a[i][j]*x[j]
     
    x[i] = x[i]/a[i][i]
    sign = '+' if t<0 else '-'
    print(f"x[{i}] = ({a[i][n]} {sign} {abs(t)})/{a[i][i]} = {x[i]}", end='\n\n')
print('\nThe solution is: ')
for i in range(n):
    print('X%d = %0.5f' %(i,x[i]), end = '\t')

<center>
<hr>
<font size="20" color='Blue' >Gauss Seidel Method</font>
<hr>
</center>

In [ ]:
mat = np.array([[25,5,1],[64,8,1],[144,12,1]])
vec_b = np.array([106.8,177.2,279.2])
print(mat)
print(vec_b)

In [ ]:
def seidel(a, x ,b):
    #Finding length of a(3)       
    n = len(a)                   
    # for loop for 3 times as to calculate x, y , z
    for j in range(0, n):        
        # temp variable d to store b[j]
        d = b[j]                  

        # to calculate respective xi, yi, zi
        for i in range(0, n):     
            if(j != i):
                d-=a[j][i] * x[i]
        # updating the value of our solution        
        x[j] = d / a[j][j]
    # returning our updated solution           
    return x    

x=[1,2,5]

for i in range(0, 10):
    x = seidel(a, x, b)
    print(x)



<font size="7" color='Black' >Not converging, however, let's see the results of example 2</font>


In [ ]:
mat = np.array([[12,3,-5],[1,5,3],[3,7,13]])
vec_b = np.array([1,28,76])
print(mat)
print(vec_b)

In [ ]:
x=[1,0,1]

for i in range(0, 10):
    x = seidel(mat, x, vec_b)
    print(f'{i}-th iteration: {x}')

<font size="7" color='Black' >It is converging...</font>


<center>
<hr>
<font size="20" color='Blue' >LU Decomposition Method </font>
<hr>
</center>

<font size="7" color='Black' >Do little Method </font>


In [ ]:
# Python3 Program to decompose
# a matrix into lower and
# upper triangular matrix
MAX = 100

def luDecomposition(mat, n):

	lower = [[0 for x in range(n)]
			for y in range(n)]
	upper = [[0 for x in range(n)]
			for y in range(n)]

	# Decomposing matrix into Upper
	# and Lower triangular matrix
	for i in range(n):

		# Upper Triangular
		for k in range(i, n):

			# Summation of L(i, j) * U(j, k)
			sum = 0
			for j in range(i):
				sum += (lower[i][j] * upper[j][k])

			# Evaluating U(i, k)
			upper[i][k] = mat[i][k] - sum

		for l in range(n):

			# Upper
			for m in range(n):
				print(upper[l][m], end="\t")
			print("")
		print("")

		# Lower Triangular
		for k in range(i, n):
			if (i == k):
				lower[i][i] = 1 # Diagonal as 1
			else:

				# Summation of L(k, j) * U(j, i)
				sum = 0
				for j in range(i):
					sum += (lower[k][j] * upper[j][i])

				# Evaluating L(k, i)
				lower[k][i] = int((mat[k][i] - sum) /
								upper[i][i])

	R = np.matmul(np.array(lower),np.array(upper))
	
	# setw is for displaying nicely
	print("Lower Triangular\t\tUpper Triangular\t\tLower*Upper")

	# Displaying the result :
	for i in range(n):

		# Lower
		for j in range(n):
			print(lower[i][j], end="\t")
		print("", end="\t")

		# Upper
		for j in range(n):
			print(upper[i][j], end="\t")
		print("", end='\t')

		# R
		for j in range(n):
			print(R[i][j], end="\t")
		print("")
	


# Driver code

mat = np.array([[25.0,5.0,1.0],[64.0,8.0,1.0],[144.0,12.0,1.0]])

luDecomposition(mat, 3)

# This code is contributed by mits


In [ ]:
import scipy.linalg
A = np.array([[25.0,5.0,1.0],[64.0,8.0,1.0],[144.0,12.0,1.0]])
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

R = np.matmul(L,U)
print(np.matmul(P,R))

<center>
<hr>
<font size="20" color='Blue' >That's the end... </font>
<hr>
</center>